#ifdef __cplusplus
extern "C" {
#endif

// declare Ruby registration method generated by SWIG in rhoelements_wrap.c
extern void Init_Rhoelements(void);

// this method executed once on start of program
void Init_Rhoelements_extension(void) {
	// execute initialization of Ruby registration (generated by SWIG)
	Init_Rhoelements();

	// You can add some code to this place:


}

#ifdef __cplusplus
} //extern "C"
#endif